name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            # Install git if not present
            sudo apt update
            sudo apt install -y git
            
            # Install Node.js using nvm
            if [ ! -d "$HOME/.nvm" ]; then
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            fi
            
            nvm install --lts
            nvm use --lts
            
            # Install PM2 globally if not present
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi
            
            # Clone or pull the repository
            if [ ! -d "mathonGo-backend45" ]; then
              git clone https://github.com/cdileep23/mathonGo-backend45
              cd mathonGo-backend45
              npm install
              
              # Create .env file (you should add these as GitHub secrets)
              touch .env
              echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
              echo "REDIS_Url=${{ secrets.REDIS_Url }}" >> .env
       
              # Add other environment variables as needed
            else
              cd mathonGo-backend45
              git pull origin main
              npm install
            fi
            
            # Restart or start the application
            pm2 restart mathongobackend || pm2 start index.js --name "mathongobackend" -- --port 4545
            pm2 save
            pm2 startup
          EOF